const de = {
  number_approved: "{number} Genehmigt",
  number_rejected: "{number} Abgelehnt",
  number_abstained: "{number} Enthaltungen",
  meeting_votes_caption:
    "Klicken Sie auf jede Zeile, um zu sehen, wie die Ratsmitglieder abgestimmt haben",
  legislation: "Gesetzgebung",
  council_decision: "Beschluss des Rates",
  votes: "Stimmen",
  meeting: "Treffen",
  persons_vote: "{name}s Stimee",
  en: "English",
  es: "Español",
  de: "Deutsche",
  keywords: "Schlüsselwörter",
  select_language: "Sprache auswählen",
  same: "gleich",
  committee: "Komitee",
  chair: "Vorsitzende",
  tenure: "Amtszeit",
  bills_sponsored: "Rechnung(en) gesponsert",
  see_documents: "Siehe Dokumente",
  jump_to_sentence_video: "Zum Satz im Video springen",
  jump_to_sentence_transcript: "Zum Satz im Transkript springen",
  search_transcript: "Transkript suchen",
  search_transcript_placeholder: "Transkript suchen...",
  number_of_results: `{number} Ergebnis(e)`,
  clear: "Löschen",
  save: "Speichern",
  about: "Über",
  search: "Suche",
  advanced_options: "Erweiterte Optionen",
  copyright_notice: "Urheberrechte © Einzelne mitwirkende, {date_range}",
  content_license_prefix: "Inhalt verfügbar unter a ",
  content_license_link: "https://creativecommons.org/licenses/by/4.0/deed.en",
  content_license_link_text: "Creative Commons Namensnennung 4.0 International License",
  tools_license_prefix: "Council Data Project werkzeuge sind lizenziert unter ",
  styled_using_prefix: "Gestylt mit ",
  artwork_provided_by_prefix: "Kunstwerk zur Verfügung gestellt von ",
  approve: "Genehmigen",
  reject: "Ablehnen",
  rejected: "Abgelehnt",
  abstain: "Verzichten",
  adopted: "Angenommen",
  in_progress: "In Bearbeitung",
  example_prefix: "Beispiel:",
  search_topic_placeholder: "Thema suchen...",
  search_city_council: "Stadtrat suchen",
  events: "Veranstaltungen",
  links: "Links",
  people: "Menschen",
  council_data_project: "Council Data Project",
  transcript: "Transkript",
  agenda: "Agenda",
  session: "Sitzung",
};

export default de;
