const de = {
  tags: "Stichworte",
  select_language: "Sprache auswählen",
  same: "gleich",
  committee: "Komitee",
  chair: "Vorsitzende",
  tenure: "Amtszeit",
  bills_sponsored: "Rechnung(en) gesponsert",
  see_documents: "Siehe Dokumente",
  jump_to_sentence_video: "Zum Satz im Video springen",
  jump_to_sentence_transcript: "Zum Satz im Transkript springen",
  search_transcript: "Transkript suchen",
  search_transcript_placeholder: "Transkript suchen...",
  number_of_results: `{number} Ergebnis(e)`,
  clear: "Löschen",
  save: "Speichern",
  about: "Über",
  search: "Suche",
  advanced_options: "Erweiterte Optionen",
  copyright_notice:
    "Teile dieses Inhalts sind ©{date_range} von einzelnen Mitwirkenden des Council Data Project. Inhalt verfügbar unter {copyright_license_type}.",
  styled_using: "Gestylt mit {style_provider}.",
  artwork_provided_by: "Kunstwerk bereitgestellt von {artwork_provider}",
  approve: "Genehmigen",
  reject: "Ablehnen",
  rejected: "Abgelehnt",
  abstain: "Verzichten",
  adopted: "Angenommen",
  in_progress: "In Bearbeitung",
  example_prefix: "Beispiel:",
  search_topic_placeholder: "Thema suchen...",
  search_city_council_transcripts: "Transkripte des Stadtrats suchen",
  events: "Veranstaltungen",
  links: "Links",
  people: "Menschen",
  council_data_project: "Council Data Project",
};

export default de;
