const de = {
  number_approved: "{number} Genehmigt",
  number_rejected: "{number} Abgelehnt",
  number_non_voting: "{number} Nicht-Abstimmen",
  meeting_votes_caption:
    "Klicken Sie auf jede Zeile, um zu sehen, wie die Ratsmitglieder abgestimmt haben",
  legislation: "Gesetzgebung",
  council_decision: "Beschluss des Rates",
  votes: "Stimmen",
  meeting: "Treffen",
  persons_vote: "{name}s Stimee",
  en: "English",
  es: "Español",
  de: "Deutsche",
  keywords: "Schlüsselwörter",
  select_language: "Sprache auswählen",
  same: "gleich",
  committee: "Komitee",
  chair: "Vorsitzende",
  tenure: "Amtszeit",
  bills_sponsored: "Rechnung(en) gesponsert",
  see_documents: "Siehe Dokumente",
  jump_to_sentence_video: "Zum Satz im Video springen",
  jump_to_sentence_transcript: "Zum Satz im Transkript springen",
  search_transcript: "Transkript suchen",
  search_transcript_placeholder: "Transkript suchen...",
  number_of_results: `{number} Ergebnis(e)`,
  clear: "Löschen",
  save: "Speichern",
  about: "Über",
  search: "Suche",
  advanced_options: "Erweiterte Optionen",
  copyright_notice: "Urheberrechte © Einzelne mitwirkende, {date_range}",
  content_license_prefix: "Inhalt verfügbar unter a ",
  content_license_link: "https://creativecommons.org/licenses/by/4.0/deed.en",
  content_license_link_text: "Creative Commons Namensnennung 4.0 International License",
  tools_license_prefix: "Council Data Project werkzeuge sind lizenziert unter ",
  styled_using_prefix: "Gestylt mit ",
  artwork_provided_by_prefix: "Kunstwerk zur Verfügung gestellt von ",
  passed: "Bestanden",
  failed: "Fehlgeschlagen",
  approve: "Genehmigen",
  reject: "Ablehnen",
  abstain_approve: "Verzichten (Genehmigt)",
  abstain_non_voting: "Verzichten (Nicht-Abstimmen)",
  abstain_reject: "Verzichten (Abgelehnt)",
  absent_approve: "Abwesend (Genehmigt)",
  absent_non_voting: "Abwesend (Nicht-Abstimmen)",
  absent_reject: "Abwesend (Abgelehnt)",
  rejected: "Abgelehnt",
  adopted: "Angenommen",
  in_progress: "In Bearbeitung",
  example_prefix: "Beispiel:",
  search_topic_placeholder: "Thema suchen...",
  search_municipality_name: "{municipality_name} suchen",
  events: "Veranstaltungen",
  links: "Links",
  people: "Menschen",
  council_data_project: "Council Data Project",
  transcript: "Transkript",
  agenda: "Agenda",
  session: "Sitzung",
  date: "Datum",
  newest_first: "Neusten zuerst",
  oldest_first: "Ältesten zuerst",
  most_relevant_first: "Das Wichtigste zuerst",
  closest_match_first: "Nächste Übereinstimmung zuerst",
  most_relevant: "Relevanteste",
  search_results: "Suchergebnisse",
  event_search_results: "Ergebnisse der Suche nach Ereignissen",
  no_results_found: "Keine Ergebnisse",
  show_more: "Zeig mehr...",
  legislation_sponsored: "Gesetzgebung gesponsert",
  menu: "Speisekarte",
  persons_voting_record: "{person_name}s Abstimmungsprotokoll",
  contact: "Kontakt",
  terms: "Begriffe",
  committee_membership: "Ausschussmitgliedschaft",
  former_committee_membership: "Ehemalige Ausschussmitgliedschaft",
  committees: "Ausschüsse",
  visit_persons_website: "Besuchen Sie {person_name}s Website",
  alternate: "Wechseln",
  councilmember: "Stadtrat/in",
  member: "Mitglied",
  council_president: "Präsident des Rates",
  vice_chair: "Stellvertretender Vorsitzender",
  supervisor: "Supervisor/in",
  active: "aktiv",
  inactive: "inaktiv",
  latest_vote: "Letzte Abstimmung",
  history: "Geschichte",
  minutes: "Protokoll",
  go_to_matter_details: "Gehen Sie zu den vollständigen Rechtsvorschriften",
  disclaimer_start: "Council Data Project nutzt",
  disclaimer_end:
    "Modell zur Generierung von Ereignistranskripten. Die erstellten Transkripte können",
  disclaimer_include_errors: "Fehler enthalten.",
  disclaimer_footer_start: "In vielen Fällen verwendet Council Data Project ein fein abgestimmtes",
  disclaimer_footer_end:
    "Modell zur Generierung von Ereignisprotokollen. Wir verstehen, dass Transkripte Fehler enthalten können. Wenn Sie ein Experte für maschinelles Lernen sind und dabei helfen möchten, unser System zum Generieren von Transkripten zu verbessern, kontaktieren Sie uns bitte auf GitHub.",
  copy_button: "Text kopieren",
  donate: "Spenden",
};

export default de;
