const en = {
  number_approved: "{number} Approved",
  number_rejected: "{number} Rejected",
  number_non_voting: "{number} Non-Voting",
  meeting_votes_caption: "Click each row to see how council members voted",
  legislation: "Legislation",
  council_decision: "Council Decision",
  votes: "Votes",
  meeting: "Meeting",
  persons_vote: "{name}'s Vote",
  en: "English",
  es: "Español",
  de: "Deutsche",
  keywords: "Keywords",
  select_language: "Select Language",
  same: "same",
  committee: "Committee",
  chair: "Chair",
  tenure: "Tenure",
  bills_sponsored: "bill(s) sponsored",
  see_documents: "See Documents",
  jump_to_sentence_video: "Jump to sentence in video",
  jump_to_sentence_transcript: "Jump to sentence in transcript",
  search_transcript: "Search transcript",
  search_transcript_placeholder: "Search transcript...",
  number_of_results: `{number} result(s)`,
  clear: "Clear",
  save: "Save",
  about: "About",
  search: "Search",
  advanced_options: "Advanced Options",
  copyright_notice: "Copyright © Individual contributors, {date_range}.",
  content_license_prefix: "Content available under a ",
  content_license_link: "https://creativecommons.org/licenses/by/4.0/",
  content_license_link_text: "Creative Commons Attribution 4.0 International License",
  tools_license_prefix: "Council Data Project tools are licensed under ",
  styled_using_prefix: "Styled using ",
  artwork_provided_by_prefix: "Artwork provided by ",
  passed: "Passed",
  failed: "Failed",
  approve: "Approve",
  reject: "Reject",
  abstain_approve: "Abstain (Approve)",
  abstain_non_voting: "Abstain (Non-Voting)",
  abstain_reject: "Abstain (Reject)",
  absent_approve: "Absent (Approve)",
  absent_non_voting: "Absent (Non-Voting)",
  absent_reject: "Absent (Reject)",
  rejected: "Rejected",
  adopted: "Adopted",
  in_progress: "In Progress",
  example_prefix: "Example: ",
  search_topic_placeholder: "Search for a topic...",
  search_municipality_name: "Search {municipality_name}",
  events: "Events",
  links: "Links",
  people: "People",
  council_data_project: "Council Data Project",
  transcript: "Transcript",
  agenda: "Agenda",
  session: "Session",
  date: "Date",
  newest_first: "Newest First",
  oldest_first: "Oldest First",
  most_relevant_first: "Most relevant first",
  closest_match_first: "Closest match first",
  most_relevant: "Most relevant",
  search_results: "Search Results",
  event_search_results: "Event search results",
  no_results_found: "No results found",
  show_more: "Show more...",
  legislation_sponsored: "Legislation Sponsored",
  menu: "Menu",
  persons_voting_record: "{person_name}'s Voting Record",
  contact: "Contact",
  terms: "Terms",
  committee_membership: "Committee Membership",
  former_committee_membership: "Former Committee Membership",
  committees: "Committees",
  visit_persons_website: "Visit {person_name}'s website",
  alternate: "Alternate",
  councilmember: "Councilmember",
  member: "Member",
  council_president: "Council President",
  vice_chair: "Vice Chair",
  supervisor: "Supervisor",
  active: "active",
  inactive: "inactive",
  latest_vote: "Latest Vote",
  history: "History",
  minutes: "Minutes",
  go_to_matter_details: "Go to Full Legislation Details",
  disclaimer_start: "To provide event transcripts at low-cost, Council Data Project uses",
  disclaimer_end: "for transcription. Event transcripts may include errors.",
  disclaimer_footer_start: "In many cases, Council Data Project utilizes a fine-tuned",
  disclaimer_footer_end:
    "model for generation of event transcripts. We understand that transcripts may include errors. If you are a machine learning expert and wish to help improve our system for generating transcripts, please reach out to us on GitHub.",
  copy_button: "Copy text",
};

export default en;
