const en = {
  number_approved: "{number} Approved",
  number_rejected: "{number} Rejected",
  number_abstained: "{number} Abstained",
  meeting_votes_caption: "Click each row to see how council members voted",
  legislation: "Legislation",
  council_decision: "Council Decision",
  votes: "Votes",
  meeting: "Meeting",
  persons_vote: "{name}'s Vote",
  en: "English",
  es: "Español",
  de: "Deutsche",
  keywords: "Keywords",
  select_language: "Select Language",
  same: "same",
  committee: "Committee",
  chair: "Chair",
  tenure: "Tenure",
  bills_sponsored: "bill(s) sponsored",
  see_documents: "See Documents",
  jump_to_sentence_video: "Jump to sentence in video",
  jump_to_sentence_transcript: "Jump to sentence in transcript",
  search_transcript: "Search transcript",
  search_transcript_placeholder: "Search transcript...",
  number_of_results: `{number} result(s)`,
  clear: "Clear",
  save: "Save",
  about: "About",
  search: "Search",
  advanced_options: "Advanced Options",
  copyright_notice: "Copyright © Individual contributors, {date_range}.",
  content_license_prefix: "Content available under a ",
  content_license_link: "https://creativecommons.org/licenses/by/4.0/",
  content_license_link_text: "Creative Commons Attribution 4.0 International License",
  tools_license_prefix: "Council Data Project tools are licensed under ",
  styled_using_prefix: "Styled using ",
  artwork_provided_by_prefix: "Artwork provided by ",
  approve: "Approve",
  reject: "Reject",
  rejected: "Rejected",
  abstain: "Abstain",
  adopted: "Adopted",
  in_progress: "In Progress",
  example_prefix: "Example: ",
  search_topic_placeholder: "Search for a topic...",
  search_city_council: "Search City Council",
  events: "Events",
  links: "Links",
  people: "People",
  council_data_project: "Council Data Project",
  transcript: "Transcript",
  agenda: "Agenda",
  session: "Session",
};

export default en;
