const es = {
  number_approved: "{number} Aprobado",
  number_rejected: "{number} Rechazado",
  number_non_voting: "{number} sin derecho a voto",
  meeting_votes_caption: "Haga clic en cada fila para ver cómo votaron los miembros del consejo",
  legislation: "Legislación",
  council_decision: "Decisión del Consejo",
  votes: "Votos",
  meeting: "Cita",
  persons_vote: "Voto de {name}",
  en: "English",
  es: "Español",
  de: "Deutsche",
  keywords: "Palabras clave",
  select_language: "Seleccione el Idioma",
  same: "Mismo",
  committee: "Comité",
  chair: "presidente",
  tenure: "Tenencia",
  bills_sponsored: "factura (s) patrocinada",
  see_documents: "Ver Documentos",
  jump_to_sentence_video: "Saltar a la oración en el video",
  jump_to_sentence_transcript: "Saltar a la oración en la transcripción",
  search_transcript: "Buscar transcripción",
  search_transcript_placeholder: "Buscar transcripción ...",
  number_of_results: `{number} resultado (s)`,
  clear: "Despejar",
  save: "Ahorrar",
  about: "Acerca de",
  search: "Buscar",
  advanced_options: "Opciones Avanzadas",
  copyright_notice: "Derechos de autor © Contribuyentes individuales, {date_range}.",
  content_license_prefix: "Contenido disponible bajo un ",
  content_license_link: "https://creativecommons.org/licenses/by/4.0/deed.es",
  content_license_link_text: "Creative Commons Atribución 4.0 Internacional License",
  tools_license_prefix: "Council Data Project las herramientas tienen licencia bajo ",
  styled_using_prefix: "Diseñado usando ",
  artwork_provided_by_prefix: "Obra proporcionada por ",
  passed: "Pasó",
  failed: "Fracasó",
  approve: "Aprobar",
  reject: "Rechazar",
  abstain_approve: "Abstenerse (Aprobado)",
  abstain_non_voting: "Abstenerse (sin derecho a voto)",
  abstain_reject: "Abstenerse (Rechazado)",
  absent_approve: "Ausente (Aprobado)",
  absent_non_voting: "Ausente (sin derecho a voto)",
  absent_reject: "Ausente (Rechazado)",
  rejected: "Rechazado",
  adopted: "Adoptado",
  in_progress: "En curso",
  example_prefix: "Ejemplo:",
  search_topic_placeholder: "Buscar un tema ...",
  search_municipality_name: "Buscar {municipality_name}",
  events: "Eventos",
  links: "Enlaces",
  people: "Gente",
  council_data_project: "Council Data Project",
  transcript: "Transcripción",
  agenda: "Agenda",
  session: "Sesión",
  date: "Fecha",
  newest_first: "Más nuevos primero",
  oldest_first: "Más viejos primero",
  most_relevant_first: "Más relevante primero",
  closest_match_first: "Coincidencia más cercana primero",
  most_relevant: "Más relevante",
  search_results: "Resultados de la Búsqueda",
  event_search_results: "Resultados de Busqueda de Eventos",
  no_results_found: "No hay resultados",
  show_more: "Mostrar más...",
  legislation_sponsored: "Legislación patrocinada",
  menu: "Menú",
  persons_voting_record: "Registro de votos de {person_name}",
  contact: "Contacto",
  terms: "Términos",
  committee_membership: "Membresía del Comité",
  former_committee_membership: "Membresía Anterior del Comité",
  committees: "Comités",
  visit_persons_website: "Visite el sitio web de {person_name}",
  alternate: "Alterno/a",
  councilmember: "Concejal/a",
  member: "Miembro",
  council_president: "Presidente/a del Consejo",
  vice_chair: "Vicepresidente/a",
  active: "activo/a",
  inactive: "inactivo/a",
  latest_vote: "Último Voto",
};

export default es;
