const es = {
  number_approved: "{number} Aprobado",
  number_rejected: "{number} Rechazado",
  number_abstained: "{number} se Abstuvo",
  meeting_votes_caption: "Haga clic en cada fila para ver cómo votaron los miembros del consejo",
  legislation: "Legislación",
  council_decision: "Decisión del Consejo",
  votes: "Votos",
  meeting: "Cita",
  persons_vote: "Voto de {name}",
  en: "English",
  es: "Español",
  de: "Deutsche",
  tags: "Etiquetas",
  select_language: "Seleccione el Idioma",
  same: "Mismo",
  committee: "Comité",
  chair: "presidente",
  tenure: "Tenencia",
  bills_sponsored: "factura (s) patrocinada",
  see_documents: "Ver Documentos",
  jump_to_sentence_video: "Saltar a la oración en el video",
  jump_to_sentence_transcript: "Saltar a la oración en la transcripción",
  search_transcript: "Buscar transcripción",
  search_transcript_placeholder: "Buscar transcripción ...",
  number_of_results: `{number} resultado (s)`,
  clear: "Despejar",
  save: "Ahorrar",
  about: "Acerca de",
  search: "Buscar",
  advanced_options: "Opciones Avanzadas",
  copyright_notice:
    "Partes de este contenido son © {date_range} de colaboradores individuales del Council Data Project. Contenido disponible bajo {copyright_license_type}.",
  styled_using: "Diseñado con {style_provider}.",
  artwork_provided_by: "Obra de arte proporcionada por {artwork_provider}.",
  approve: "Aprobar",
  reject: "Rechazar",
  rejected: "Rechazado",
  abstain: "Abstenerse",
  adopted: "Adoptado",
  in_progress: "En curso",
  example_prefix: "Ejemplo:",
  search_topic_placeholder: "Buscar un tema ...",
  search_city_council: "Buscar Ayuntamiento",
  events: "Eventos",
  links: "Enlaces",
  people: "Gente",
  council_data_project: "Council Data Project",
  transcript: "Transcripción",
  agenda: "Agenda",
  session: "Sesión",
};

export default es;
