const es = {
  number_approved: "{number} Aprobado",
  number_rejected: "{number} Rechazado",
  number_abstained: "{number} se Abstuvo",
  meeting_votes_caption: "Haga clic en cada fila para ver cómo votaron los miembros del consejo",
  legislation: "Legislación",
  council_decision: "Decisión del Consejo",
  votes: "Votos",
  meeting: "Cita",
  persons_vote: "Voto de {name}",
  en: "English",
  es: "Español",
  de: "Deutsche",
  keywords: "Palabras clave",
  select_language: "Seleccione el Idioma",
  same: "Mismo",
  committee: "Comité",
  chair: "presidente",
  tenure: "Tenencia",
  bills_sponsored: "factura (s) patrocinada",
  see_documents: "Ver Documentos",
  jump_to_sentence_video: "Saltar a la oración en el video",
  jump_to_sentence_transcript: "Saltar a la oración en la transcripción",
  search_transcript: "Buscar transcripción",
  search_transcript_placeholder: "Buscar transcripción ...",
  number_of_results: `{number} resultado (s)`,
  clear: "Despejar",
  save: "Ahorrar",
  about: "Acerca de",
  search: "Buscar",
  advanced_options: "Opciones Avanzadas",
  copyright_notice: "Derechos de autor © Contribuyentes individuales, {date_range}.",
  content_license_prefix: "Contenido disponible bajo un ",
  content_license_link: "https://creativecommons.org/licenses/by/4.0/deed.es",
  content_license_link_text: "Creative Commons Atribución 4.0 Internacional License",
  tools_license_prefix: "Council Data Project las herramientas tienen licencia bajo ",
  styled_using_prefix: "Diseñado usando ",
  artwork_provided_by_prefix: "Obra proporcionada por ",
  approve: "Aprobar",
  reject: "Rechazar",
  rejected: "Rechazado",
  abstain: "Abstenerse",
  adopted: "Adoptado",
  in_progress: "En curso",
  example_prefix: "Ejemplo:",
  search_topic_placeholder: "Buscar un tema ...",
  search_city_council: "Buscar Ayuntamiento",
  events: "Eventos",
  links: "Enlaces",
  people: "Gente",
  council_data_project: "Council Data Project",
  transcript: "Transcripción",
  agenda: "Agenda",
  session: "Sesión",
  passed: "Passed",
  failed: "Failed",
};

export default es;
